= LionWeb Notification System API

This document explains the LionWeb notification system API through some use cases.

== Use cases

=== How to get informed about changes

Every partition node (aka root node) of a model, which supports notification API, triggers a notification when there is a change to the model.
In the example below, a partition is connected to a receiver. Receiver will be informed about all the changes to the partition via notifications.
In this case, receiver (see `NotificationCounter` class definition below) counts the received notifications in its `Receive` method.

Code below gives an example of API usage demonstrating how to get informed about changes to a partition.

[,csharp]
----
include::../test/LionWeb.Core.Test/Notification/NotificationApiUseCaseExamples.cs[tag=partition_changes]
----
<1> If notifications are not supported, `partition.GetNotificationSender()` returns null.
<2> This is a change to the model.

Code below gives an example of API usage demonstrating how to get informed about changes to a forest.
A forest is a collection of model trees, represented by each tree's partition.

[,csharp]
----
include::../test/LionWeb.Core.Test/Notification/NotificationApiUseCaseExamples.cs[tag=forest_changes]
----
<1> If notifications are not supported, `partition.GetNotificationSender()` returns null.
<2> This is a change to the forest. A partition is added to the forest.

[,csharp]
----
include::../test/LionWeb.Core.Test/Notification/NotificationApiUseCaseExamples.cs[tag=notification_counter]
----

=== How to collect multiple changes into one change set

Notifications raised by multiple changes to a model can be collected into one change set.
A `NotificationCompositor` composes other forest and/or partition notifications into one
`CompositeNotification`. Follow the comments below further explanation.

[,csharp]
----
include::../test/LionWeb.Core.Test/Notification/NotificationApiUseCaseExamples.cs[tag=composite_notification]
----
<1> If notifications are not supported, `partition.GetNotificationSender()`  returns null.
<2> Connects partition notification sender to compositor.
<3> Push creates a new composite notification to collect incoming notifications.
<4> Updates take place.
<5> Pop returns the composite notification.
<6> Access the notifications (changes).

`UpdateDocumentation` is the method that applies changes to the partition.

[,csharp]
----
include::../test/LionWeb.Core.Test/Notification/NotificationApiUseCaseExamples.cs[tag=update_documentation]
----
<1> First change to the partition.
<2> Second change to the partition.

=== How to replicate changes

==== Partition replicator

Partition replicator replicates received changes (via notifications) on a local equivalent partition. +
Follow the comments below for further explanation.

[,csharp]
----
include::../test/LionWeb.Core.Test/Notification/NotificationApiUseCaseExamples.cs[tags=partition_replicator_1;partition_replicator_2]
----
<1> Changes will be applied to this local partition.
<2> `ReplicateChangesOn` replicates the received changes on local partition. 

[,csharp]
----
include::../test/LionWeb.Core.Test/Notification/NotificationApiUseCaseExamples.cs[tag=replicate_changes_on]
----
<1> Creates a partition replicator. The SharedNodeMap keeps mapping of `NodeId` and `IReadableNode` pair shared between all notification pipes in one client or repository.
<2> Creator simulates a notification producer.
<3> Replicator will receive changes form the creator.
<4> Creator sends changes to the replicator.

[,csharp]
----
include::../test/LionWeb.Core.Test/Notification/NotificationApiUseCaseExamples.cs[tag=creator]
----

==== Forest replicator
Forest replicator replicates notifications for a local forest and all its partitions. It works exactly the same way as for one partition. User needs to use `ForestReplicator.Create` helper method to create a forest replicator (instead of `PartitionReplicator.Create`).   


