name: CI LionWeb-C#

on:
  workflow_dispatch:
  pull_request:
  push:
    tags:
      - '*'

env:
  NuGetDirectory: ${{github.workspace}}/nuget

defaults:
  run:
    shell: pwsh

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup .NET
        uses: actions/setup-dotnet@v4

      - name: Restore dependencies for all projects
        run: dotnet restore

      - name: Build all projects
        run: dotnet build

      - name: Test all projects
        run: dotnet test --logger:nunit

      - name: Pack NuGet packages
        run: |
          foreach ($packageDir in (Get-ChildItem src/)) {
            dotnet pack --configuration Release --output ${{env.NuGetDirectory}} $packageDir
          }

      - name: Publish NuGet packages
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          foreach ($packageFile in (Get-ChildItem "${{env.NuGetDirectory}}" -Recurse -Include *.nupkg)) {
              dotnet nuget push $packageFile --api-key "${{secrets.NUGET_APIKEY}}" --source https://api.nuget.org/v3/index.json --skip-duplicate
          }

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: |
            TEST-*.xml
          large_files: "true"
          report_individual_runs: "true"
          report_suite_logs: "any"
          check_run_annotations: all tests, skipped tests
          action_fail: "true"
