name: Build LionWeb-C#

on:
  workflow_dispatch:
  push:
    branches:
      - '*'
    tags:
      - '*'

env:
  NuGetDirectory: ${{github.workspace}}/nuget

defaults:
  run:
    shell: pwsh

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Get all history to allow automatic versioning using MinVer
          # TODO  can we set this to 1 since we only need a tag?

      - name: Setup .NET
        uses: actions/setup-dotnet@v4

      - name: Restore dependencies for all projects
        run: dotnet restore

      - name: Build all projects
        run: dotnet build

      - name: Test all projects
        run: dotnet test

      - name: Pack NuGet package LionWeb-CSharp
        run: dotnet pack --configuration Release --output ${{env.NuGetDirectory}} src/LionWeb-CSharp

      - name: Pack NuGet package LionWeb-CSharp
        run: dotnet pack --configuration Release --output ${{env.NuGetDirectory}} src/LionWeb-CSharp-Generator

      - name: Publish NuGet packages
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          foreach($file in (Get-ChildItem "${{env.NuGetDirectory}}" -Recurse -Include *.nupkg)) {
              dotnet nuget push $file --api-key "${{ secrets.NUGET_APIKEY }}" --source https://api.nuget.org/v3/index.json --skip-duplicate
          }

